In [ ]:
!unzip "/content/drive/MyDrive/data for big data storage/data-v2.zip"

Archive:  /content/drive/MyDrive/data for big data storage/data-v2.zip
   creating: data-v2/
  inflating: data-v2/multichain_wallets.csv
  inflating: data-v2/projects.csv
  inflating: data-v2/smart_contracts.csv
  inflating: data-v2/token_transfer.csv
  inflating: data-v2/wallets.csv

In [ ]:
import pandas as pd

multichain_wallets = pd.read_csv("/content/data-v2/multichain_wallets.csv", index_col=None)
projects = pd.read_csv("/content/data-v2/projects.csv", index_col=None)
projects = projects.rename(columns = {i:i + "_project" for i in projects.columns})
smart_contracts = pd.read_csv("/content/data-v2/smart_contracts.csv", index_col=None)
smart_contracts = smart_contracts.rename(columns = {i:i + "_contract" for i in smart_contracts.columns})
token_transfer = pd.read_csv("/content/data-v2/token_transfer.csv", index_col=None)
token_transfer = token_transfer.rename(columns = {i:i + "_transact" for i in token_transfer.columns})
wallets = pd.read_csv("/content/data-v2/wallets.csv",index_col=None)

In [ ]:
print(multichain_wallets.columns)
# set(multichain_wallets["totalValueOfLiquidation"])

Index(['Unnamed: 0', '_id', 'address', 'tokens', 'balanceInUSD',
       'tokenChangeLogs', 'balanceChangeLogs', 'borrowChangeLogs',
       'borrowInUSD', 'borrowTokenChangeLogs', 'borrowTokens',
       'dailyNumberOfTransactions', 'dailyTransactionAmounts',
       'depositChangeLogs', 'depositInUSD', 'depositTokenChangeLogs',
       'depositTokens', 'liquidationLogs', 'numberOfLiquidation',
       'totalValueOfLiquidation', 'flagged'],
      dtype='object')

In [ ]:
print(projects.columns)
print(len(projects))
# projects[projects["idDApp"].notna()]
# a = projects[projects["contractAddresses"].notna()]["contractAddresses"].tolist()
# len(a)
# projects['new_addresses_project'] = projects['new_addresses_project'].apply(lambda x: eval(x))
# projects = projects.explode('new_addresses_project')
projects = projects.explode('new_addresses_project')
# sum([len(eval(i)) for i in a])

Index(['Unnamed: 0_project', '_id_project', 'idDApp_project', 'imgUrl_project',
       'name_project', 'category_project', 'deployedChains_project',
       'numberOfUsers_project', 'numberOfTransactions_project',
       'transactionVolume_project', 'socialSignal_project', 'sources_project',
       'id_project', 'tvl_project', 'subprojects_project',
       'idDefiLlama_project', 'rankTVL_project', 'marketShare_project',
       'tvlChangeLogs_project', 'lastUpdated_project', 'lastUpdatedAt_project',
       'idOpensea_project', 'price_project', 'volume_project',
       'volumeChangeRate_project', 'numberOfOwners_project',
       'numberOfItems_project', 'numberOfListedItems_project',
       'priceChangeLogs_project', 'volumeChangeLogs_project', 'links_project',
       'description_project', 'infoChecked_project', 'nftAddresses_project',
       'tokenAddresses_project', 'rankNFT_project', 'marketShareNFT_project',
       'idBinance_project', 'priceChangeRate_project', 'tvlChangeRate_project',
       'idCMC_project', 'dexVolume_project', 'launchedAt_project',
       'dexVolumeChangeLogs_project', 'socialAccounts_project',
       'spotVolume_project', 'derivativeVolume_project',
       'spotVolumeChangeLogs_project', 'derivativeVolumeChangeLogs_project',
       'rankExchange_project', 'marketShareExchange_project',
       'tradingVolume_project', 'tradingVolumeChangeLogs_project',
       'symbol_project', 'forkedFrom_project', 'rankDefi_project',
       'marketShareDefi_project', 'capPerTVL_project', 'coinId_project',
       'contractAddresses_project', 'tvlByChains_project',
       'tvlByChainsChangeLogs_project', 'parentProtocol_project',
       'totalUsers_project', 'totalUsersByChains_project',
       'avgLiquidity_project', 'weeklyVisits_project', 'spotMarkets_project',
       'numberOfCoin_project', 'fiatSupported_project',
       'spotVolumeGraph_project', 'numberOfCoins_project',
       'spotVolumeGraphIncrease_project', 'supportedTokenAddresses_project',
       'spotVolumeChangeRate_project', 'walletAddresses_project',
       'makerFeesRate_project', 'takerFeesRate_project',
       'derivativeMarkets_project', 'openInterests_project',
       'oldImgUrl_project', 'derivativeVolumeChangeRate_project',
       'dexVolumeChangeRate_project', 'deployChains_project',
       'new_addresses_project'],
      dtype='object')
292

In [ ]:
attri = "token_contract"
smart_contracts[smart_contracts[attri].notnull()][attri].drop_duplicates().tolist()

[True]

In [ ]:
print(smart_contracts.columns)
print(len(smart_contracts))
# smart_contracts.head(5)

Index(['Unnamed: 0_contract', '_id_contract', 'address_contract',
       'chainId_contract', 'numberOfLastDayCalls_contract',
       'numberOfLastDayActiveUsers_contract', 'numberOfDailyCalls_contract',
       'numberOfThisMonthCalls_contract', 'lastUpdatedAt_contract',
       'numberOfDailyActiveUsers_contract', 'checkTag_contract',
       'tags_contract', 'name_contract', 'projectDapp_contract',
       'tokenDailyTransfers_contract', 'idCoingecko_contract',
       'keyABI_contract', 'symbol_contract', 'decimals_contract',
       'imgUrl_contract', 'socialAccounts_contract', 'lastUpdated_contract',
       'categories_contract', 'price_contract', 'marketCap_contract',
       'tradingVolume_contract', 'priceChangeLogs_contract',
       'marketCapChangeLogs_contract', 'tradingVolumeChangeLogs_contract',
       'priceChangeRate_contract', 'numberOfHolders_contract',
       'totalSupply_contract', 'abi_contract', 'createdAt_contract',
       'exchanges_contract', 'project_contract', 'url_contract',
       'last_updated_at_contract', 'tokenHealth_contract',
       'lendingInfo_contract', 'contracts_contract', 'rewardToken_contract',
       'isNew_contract', 'token_contract', 'note_contract',
       'topHolders_contract', 'fee_contract'],
      dtype='object')
4275

In [ ]:
print(token_transfer.columns)
# token_transfer.head(5)

Index(['Unnamed: 0_transact', 'contract_address_transact',
       'transaction_hash_transact', 'log_index_transact',
       'block_number_transact', 'from_address_transact', 'to_address_transact',
       'value_transact'],
      dtype='object')

In [ ]:
print(wallets.columns)
print(len(wallets))
# wallets.head(5)

Index(['Unnamed: 0', '_id', 'address', 'chainId', 'dailyAllTransactions',
       'tokens', 'balanceInUSD', 'tokenChangeLogs', 'balanceChangeLogs',
       'borrowChangeLogs', 'borrowInUSD', 'borrowTokenChangeLogs',
       'borrowTokens', 'dailyNumberOfTransactions', 'dailyTransactionAmounts',
       'depositChangeLogs', 'depositInUSD', 'depositTokenChangeLogs',
       'depositTokens', 'liquidationLogs', 'numberOfLiquidation',
       'totalValueOfLiquidation', 'flagged'],
      dtype='object')
6090

In [ ]:
# # projects["contractAddresses"] = projects["contractAddresses"].apply(lambda x: list(eval(x)))
# pro = projects.explode('contractAddresses')
# pro

# Merge

In [ ]:
project_constract = projects.merge(smart_contracts, left_on = 'new_addresses_project', right_on="_id_contract",how = "inner")
project_constract

,Unnamed: 0_project,_id_project,idDApp_project,imgUrl_project,name_project,category_project,deployedChains_project,numberOfUsers_project,numberOfTransactions_project,transactionVolume_project,...,last_updated_at_contract,tokenHealth_contract,lendingInfo_contract,contracts_contract,rewardToken_contract,isNew_contract,token_contract,note_contract,topHolders_contract,fee_contract
0,483,convex-finance,NaN,https://icons.llama.fi/convex-finance.jpg,Convex Finance,Yield,"['0x1', '0x89', '0xa4b1']",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,483,convex-finance,NaN,https://icons.llama.fi/convex-finance.jpg,Convex Finance,Yield,"['0x1', '0x89', '0xa4b1']",NaN,NaN,NaN,...,1.668929e+09,252.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,483,convex-finance,NaN,https://icons.llama.fi/convex-finance.jpg,Convex Finance,Yield,"['0x1', '0x89', '0xa4b1']",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,483,convex-finance,NaN,https://icons.llama.fi/convex-finance.jpg,Convex Finance,Yield,"['0x1', '0x89', '0xa4b1']",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,483,convex-finance,NaN,https://icons.llama.fi/convex-finance.jpg,Convex Finance,Yield,"['0x1', '0x89', '0xa4b1']",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4349,24319,venus-core-pool,NaN,https://icons.llama.fi/venus-core-pool.jpg,Venus Core Pool,Lending,['0x38'],NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4350,24319,venus-core-pool,NaN,https://icons.llama.fi/venus-core-pool.jpg,Venus Core Pool,Lending,['0x38'],NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4351,24319,venus-core-pool,NaN,https://icons.llama.fi/venus-core-pool.jpg,Venus Core Pool,Lending,['0x38'],NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4352,24319,venus-core-pool,NaN,https://icons.llama.fi/venus-core-pool.jpg,Venus Core Pool,Lending,['0x38'],NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4353,25136,nova-pepe-1,NaN,https://i.seadn.io/s/raw/files/8c4e88c50322d0d...,Nova Pepe,Art,['0xa4b1'],NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
transact_project = project_constract.merge(token_transfer, left_on="address_contract", right_on="contract_address_transact", how="inner")
transact_project

,Unnamed: 0_project,_id_project,idDApp_project,imgUrl_project,name_project,category_project,deployedChains_project,numberOfUsers_project,numberOfTransactions_project,transactionVolume_project,...,topHolders_contract,fee_contract,Unnamed: 0_transact,contract_address_transact,transaction_hash_transact,log_index_transact,block_number_transact,from_address_transact,to_address_transact,value_transact
0,500,mummy-finance,NaN,https://icons.llama.fi/mummy-finance.jpg,Mummy Finance,Derivatives,"['0xfa', '0xa', '0xa4b1']",NaN,NaN,NaN,...,NaN,NaN,14,0xa6d7d0e650aa40ffa42d845a354c12c2bc0ab15f,0x1b9d73e69e67aafa913d88012f19e9be315509f5340c...,1,129956639,0x0000000000000000000000000000000000000000,0xacd54246eda0c5638a247c4717a8782c21497eb6,0.150000
1,500,mummy-finance,NaN,https://icons.llama.fi/mummy-finance.jpg,Mummy Finance,Derivatives,"['0xfa', '0xa', '0xa4b1']",NaN,NaN,NaN,...,NaN,NaN,227,0xa6d7d0e650aa40ffa42d845a354c12c2bc0ab15f,0x3431b0ee2ac1da01e073d7bb4a8410555ad906783d4c...,0,129960577,0xacd54246eda0c5638a247c4717a8782c21497eb6,0x0000000000000000000000000000000000000000,0.150000
2,500,mummy-finance,NaN,https://icons.llama.fi/mummy-finance.jpg,Mummy Finance,Derivatives,"['0xfa', '0xa', '0xa4b1']",NaN,NaN,NaN,...,NaN,NaN,392,0xa6d7d0e650aa40ffa42d845a354c12c2bc0ab15f,0x231a2d6829bd755be025228735b53cc0d0a463629d68...,1,129962172,0x0000000000000000000000000000000000000000,0xacd54246eda0c5638a247c4717a8782c21497eb6,0.150000
3,500,mummy-finance,NaN,https://icons.llama.fi/mummy-finance.jpg,Mummy Finance,Derivatives,"['0xfa', '0xa', '0xa4b1']",NaN,NaN,NaN,...,NaN,NaN,753,0xa6d7d0e650aa40ffa42d845a354c12c2bc0ab15f,0x41a7e6480efc5158f82b949e2f9f53057f413c671017...,10,129966338,0x0000000000000000000000000000000000000000,0x7f7835dfe1f050f48597380551d5d2ef792d50bf,24.164214
4,500,mummy-finance,NaN,https://icons.llama.fi/mummy-finance.jpg,Mummy Finance,Derivatives,"['0xfa', '0xa', '0xa4b1']",NaN,NaN,NaN,...,NaN,NaN,779,0xa6d7d0e650aa40ffa42d845a354c12c2bc0ab15f,0xedf113a9693f433f36549431b61e3c065cef9b9a140f...,0,129966606,0x7f7835dfe1f050f48597380551d5d2ef792d50bf,0x0000000000000000000000000000000000000000,24.164214
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705049,14504,chronos,NaN,https://s2.coinmarketcap.com/static/img/exchan...,Chronos,Dexes,['0xa4b1'],NaN,NaN,NaN,...,NaN,NaN,71639,0x07bcb73177c800bd53a38818cecd3fd4da8262f5,0x9c06a53ff81b6a491637dad066d646a4e86c1e6ccbcc...,4,132026625,0x0000000000000000000000000000000000000000,0xa668e2805a50ca0cc73ed66a131e15522ac093f8,0.234487
705050,14504,chronos,NaN,https://s2.coinmarketcap.com/static/img/exchan...,Chronos,Dexes,['0xa4b1'],NaN,NaN,NaN,...,NaN,NaN,483559,0x07bcb73177c800bd53a38818cecd3fd4da8262f5,0x04947e5b69d218f831eb090dba1a87d146e926161f2c...,21,138072567,0x0000000000000000000000000000000000000000,0x7a80dcb3e09966b540f48d870111ea21c844a27e,426.004634
705051,14504,chronos,NaN,https://s2.coinmarketcap.com/static/img/exchan...,Chronos,Dexes,['0xa4b1'],NaN,NaN,NaN,...,NaN,NaN,483571,0x07bcb73177c800bd53a38818cecd3fd4da8262f5,0xe1fe13e8bbe6fa63bf6f5a6a6169f4a1934bc052ea71...,3,138072704,0x7a80dcb3e09966b540f48d870111ea21c844a27e,0x266dd44d981e5bca81d7a0fdadb051b2f411509b,426.004634
705052,14504,chronos,NaN,https://s2.coinmarketcap.com/static/img/exchan...,Chronos,Dexes,['0xa4b1'],NaN,NaN,NaN,...,NaN,NaN,498042,0x07bcb73177c800bd53a38818cecd3fd4da8262f5,0xc1b1d453b2a0d6c8bbadf3496846776c020af973b838...,3,138337464,0x0000000000000000000000000000000000000000,0x4faf1763dc8ce17ff1752366cbfbc3912ce7bd27,356.860618
705053,14504,chronos,NaN,https://s2.coinmarketcap.com/static/img/exchan...,Chronos,Dexes,['0xa4b1'],NaN,NaN,NaN,...,NaN,NaN,498050,0x07bcb73177c800bd53a38818cecd3fd4da8262f5,0x45948809f8b61f2096c8cd9d6d71b2cf3a628e9c38fd...,0,138337674,0x4faf1763dc8ce17ff1752366cbfbc3912ce7bd27,0x266dd44d981e5bca81d7a0fdadb051b2f411509b,356.860618

In [ ]:
wallet_project = wallets.merge(transact_project, left_on ="address", right_on="from_address_transact", how='left')
wallet_project["is_sender"] = wallet_project['from_address_transact'].notnull()
wallet_project

,Unnamed: 0,_id,address,chainId,dailyAllTransactions,tokens,balanceInUSD,tokenChangeLogs,balanceChangeLogs,borrowChangeLogs,...,fee_contract,Unnamed: 0_transact,contract_address_transact,transaction_hash_transact,log_index_transact,block_number_transact,from_address_transact,to_address_transact,value_transact,is_sender
0,0,0xa4b1_0x13f54c374a08137f542482358e2e9677c3eedce3,0x13f54c374a08137f542482358e2e9677c3eedce3,0xa4b1,"{'1688860800': 11, '1691366400': 5, '169145280...",{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,42.896319,{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,"{'1698105600': 1.1134835866233035, '1698192000...","{'1688943589': 0.0, '1688943717': 699.8712, '1...",...,NaN,464377.0,0x8619d80fb0141ba7f184cbf22fd724116d9f7ffc,0x80a10325f3a223fdeaff60aefc7e7348d139ab77d4ac...,0.0,137752197.0,0x13f54c374a08137f542482358e2e9677c3eedce3,0x0000000000000000000000000000000000000000,1002.165002,True
1,0,0xa4b1_0x13f54c374a08137f542482358e2e9677c3eedce3,0x13f54c374a08137f542482358e2e9677c3eedce3,0xa4b1,"{'1688860800': 11, '1691366400': 5, '169145280...",{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,42.896319,{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,"{'1698105600': 1.1134835866233035, '1698192000...","{'1688943589': 0.0, '1688943717': 699.8712, '1...",...,NaN,464377.0,0x8619d80fb0141ba7f184cbf22fd724116d9f7ffc,0x80a10325f3a223fdeaff60aefc7e7348d139ab77d4ac...,0.0,137752197.0,0x13f54c374a08137f542482358e2e9677c3eedce3,0x0000000000000000000000000000000000000000,1002.165002,True
2,0,0xa4b1_0x13f54c374a08137f542482358e2e9677c3eedce3,0x13f54c374a08137f542482358e2e9677c3eedce3,0xa4b1,"{'1688860800': 11, '1691366400': 5, '169145280...",{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,42.896319,{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,"{'1698105600': 1.1134835866233035, '1698192000...","{'1688943589': 0.0, '1688943717': 699.8712, '1...",...,NaN,464377.0,0x8619d80fb0141ba7f184cbf22fd724116d9f7ffc,0x80a10325f3a223fdeaff60aefc7e7348d139ab77d4ac...,0.0,137752197.0,0x13f54c374a08137f542482358e2e9677c3eedce3,0x0000000000000000000000000000000000000000,1002.165002,True
3,0,0xa4b1_0x13f54c374a08137f542482358e2e9677c3eedce3,0x13f54c374a08137f542482358e2e9677c3eedce3,0xa4b1,"{'1688860800': 11, '1691366400': 5, '169145280...",{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,42.896319,{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,"{'1698105600': 1.1134835866233035, '1698192000...","{'1688943589': 0.0, '1688943717': 699.8712, '1...",...,NaN,464377.0,0x8619d80fb0141ba7f184cbf22fd724116d9f7ffc,0x80a10325f3a223fdeaff60aefc7e7348d139ab77d4ac...,0.0,137752197.0,0x13f54c374a08137f542482358e2e9677c3eedce3,0x0000000000000000000000000000000000000000,1002.165002,True
4,0,0xa4b1_0x13f54c374a08137f542482358e2e9677c3eedce3,0x13f54c374a08137f542482358e2e9677c3eedce3,0xa4b1,"{'1688860800': 11, '1691366400': 5, '169145280...",{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,42.896319,{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,"{'1698105600': 1.1134835866233035, '1698192000...","{'1688943589': 0.0, '1688943717': 699.8712, '1...",...,NaN,464377.0,0x8619d80fb0141ba7f184cbf22fd724116d9f7ffc,0x80a10325f3a223fdeaff60aefc7e7348d139ab77d4ac...,0.0,137752197.0,0x13f54c374a08137f542482358e2e9677c3eedce3,0x0000000000000000000000000000000000000000,1002.165002,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72232,8489,0xa4b1_0xa4420ebbce47b452ff68d0ffa4efc8cac75655eb,0xa4420ebbce47b452ff68d0ffa4efc8cac75655eb,0xa4b1,"{'1688688000': 5, '1689465600': 4, '1689638400...",{'0x912ce59144191c1204e64559fe8253a0e49e6548':...,27.317898,{'0x912ce59144191c1204e64559fe8253a0e49e6548':...,"{'1698105600': 1914.176645849158, '1698192000'...","{'1688728407': 0.0, '1691262707': 0.0, '169126...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
72233,8492,0xa4b1_0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xa4b1,"{'1688688000': 4, '1688774400': 2, '1690588800...",{'0x031d35296154279dc1984dcd93e392b1f946737b':...,754.837425,{'0x031d35296154279dc1984dcd93e392b1f946737b':...,"{'1698105600': 21.30410633999788, '1698192000'...","{'1695903758': 0.0, '1695903931': 1047.4915120...",...,NaN,351944.0,0x6694340fc020c5e6b96567843da2df01b2ce1eb6,0xe92eb1eda1e4fd029d2cdc52447dda56b072a8919cb5...,10.0,135970802.0,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xd49de5771d82ffe9691aa26f47766a15588acaa2,3.986631,True
72234,8492,0xa4b1_0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xa4b1,"{'1688688000': 4, '1688774400': 2, '1690588800...",{'0x031d35296154279dc1984dcd93e392b1f946737b':...,754.837425,{'0x031d35296154279dc1984dcd93e392b1f946737b':...,"{'1698105600': 21.30410633999788, '1698192000'...","{'1695903758': 0.0, '1695903931': 1047.4915120...",...,NaN,331183.0,0x0df5dfd95966753f01cb80e76dc20ea958238c46,0xb86c468f4ed96b4396c0b240227054c5205f2cb32904...,11.0,135656205.0,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xbb5ca40b2f7af3b1ff5dbce0e9cc78f8bfa817ce,1.300037,True
72235,8492,0xa4b1_0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xa4b1,"{'1688688000': 4, '1688774400': 2, '1690588800...",{'0x031d35296154279dc1984dcd93e392b1f946737b':...,754.837425,{'0x031d35296154279dc1984dcd93e392b1f946737b':...,"{'1698105600': 21.30410633999788, '1698192000'...","{'1695903758': 0.0, '1695903931': 1047.4915120...",...,NaN,320143.0,0x107583adaa37dfd1cc0bf577183bf91351d07413,0x9ac37302a68925408c3a8932bae720afec45692bebab...,21.0,135456110.0,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0x0000000000000000000000000000000000000000,1046.465745,True
72236,8493,0xa4b1_0xa841791f529f46755e129b0e16ec624e28f4c1ce,0xa841791f529f46755e129b0e16ec624e28f4c1ce,0xa4b1,"{'1688688000': 1, '1689206400': 5, '1690156800...",{'0x289ba1701c2f088cf0faf8b3705246331cb8a839':...,2.905276,{'0x289ba1701c2f088cf0faf8b3705246331cb8a839':...,"{'1698105600': 0.0, '1698192000': 2.3878833419...","{'1693393374': 0.0, '1693393484': 0.0, '169544...",...,NaN,207790.0,0x2dade5b7df9da3a7e1c9748d169cd6dff77e3d01,0x4acb4e619fb375e51f883140e8fa21d5d683b34ecb1b...,5.0,133715410.0,0xa841791f529f46755e129b0e16ec624e28f4c1ce,0x0000000000000000000000000000000000000000,374.000000,True

In [ ]:
wallet_project_1 = wallets.merge(transact_project, left_on ="address", right_on="to_address_transact", how='left',suffixes=('_receiver',''))
wallet_project_1["is_receiver"] = wallet_project_1['to_address_transact'].notnull()
wallet_project_1

,Unnamed: 0,_id,address,chainId,dailyAllTransactions,tokens,balanceInUSD,tokenChangeLogs,balanceChangeLogs,borrowChangeLogs,...,fee_contract,Unnamed: 0_transact,contract_address_transact,transaction_hash_transact,log_index_transact,block_number_transact,from_address_transact,to_address_transact,value_transact,is_receiver
0,0,0xa4b1_0x13f54c374a08137f542482358e2e9677c3eedce3,0x13f54c374a08137f542482358e2e9677c3eedce3,0xa4b1,"{'1688860800': 11, '1691366400': 5, '169145280...",{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,42.896319,{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,"{'1698105600': 1.1134835866233035, '1698192000...","{'1688943589': 0.0, '1688943717': 699.8712, '1...",...,NaN,20063.0,0xe50fa9b3c56ffb159cb0fca61f5c9d750e8128c8,0x748841aa37c66aa61474d8750a4db89999a854b9a318...,4.0,130154549.0,0x0000000000000000000000000000000000000000,0x13f54c374a08137f542482358e2e9677c3eedce3,0.145096,True
1,0,0xa4b1_0x13f54c374a08137f542482358e2e9677c3eedce3,0x13f54c374a08137f542482358e2e9677c3eedce3,0xa4b1,"{'1688860800': 11, '1691366400': 5, '169145280...",{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,42.896319,{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,"{'1698105600': 1.1134835866233035, '1698192000...","{'1688943589': 0.0, '1688943717': 699.8712, '1...",...,NaN,20063.0,0xe50fa9b3c56ffb159cb0fca61f5c9d750e8128c8,0x748841aa37c66aa61474d8750a4db89999a854b9a318...,4.0,130154549.0,0x0000000000000000000000000000000000000000,0x13f54c374a08137f542482358e2e9677c3eedce3,0.145096,True
2,0,0xa4b1_0x13f54c374a08137f542482358e2e9677c3eedce3,0x13f54c374a08137f542482358e2e9677c3eedce3,0xa4b1,"{'1688860800': 11, '1691366400': 5, '169145280...",{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,42.896319,{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,"{'1698105600': 1.1134835866233035, '1698192000...","{'1688943589': 0.0, '1688943717': 699.8712, '1...",...,NaN,20063.0,0xe50fa9b3c56ffb159cb0fca61f5c9d750e8128c8,0x748841aa37c66aa61474d8750a4db89999a854b9a318...,4.0,130154549.0,0x0000000000000000000000000000000000000000,0x13f54c374a08137f542482358e2e9677c3eedce3,0.145096,True
3,0,0xa4b1_0x13f54c374a08137f542482358e2e9677c3eedce3,0x13f54c374a08137f542482358e2e9677c3eedce3,0xa4b1,"{'1688860800': 11, '1691366400': 5, '169145280...",{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,42.896319,{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,"{'1698105600': 1.1134835866233035, '1698192000...","{'1688943589': 0.0, '1688943717': 699.8712, '1...",...,NaN,20063.0,0xe50fa9b3c56ffb159cb0fca61f5c9d750e8128c8,0x748841aa37c66aa61474d8750a4db89999a854b9a318...,4.0,130154549.0,0x0000000000000000000000000000000000000000,0x13f54c374a08137f542482358e2e9677c3eedce3,0.145096,True
4,0,0xa4b1_0x13f54c374a08137f542482358e2e9677c3eedce3,0x13f54c374a08137f542482358e2e9677c3eedce3,0xa4b1,"{'1688860800': 11, '1691366400': 5, '169145280...",{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,42.896319,{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,"{'1698105600': 1.1134835866233035, '1698192000...","{'1688943589': 0.0, '1688943717': 699.8712, '1...",...,NaN,20063.0,0xe50fa9b3c56ffb159cb0fca61f5c9d750e8128c8,0x748841aa37c66aa61474d8750a4db89999a854b9a318...,4.0,130154549.0,0x0000000000000000000000000000000000000000,0x13f54c374a08137f542482358e2e9677c3eedce3,0.145096,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114829,8489,0xa4b1_0xa4420ebbce47b452ff68d0ffa4efc8cac75655eb,0xa4420ebbce47b452ff68d0ffa4efc8cac75655eb,0xa4b1,"{'1688688000': 5, '1689465600': 4, '1689638400...",{'0x912ce59144191c1204e64559fe8253a0e49e6548':...,27.317898,{'0x912ce59144191c1204e64559fe8253a0e49e6548':...,"{'1698105600': 1914.176645849158, '1698192000'...","{'1688728407': 0.0, '1691262707': 0.0, '169126...",...,NaN,201669.0,0xd69d402d1bdb9a2b8c3d88d98b9ceaf9e4cd72d9,0x56c6401129b4f703996e63f21e4529d07808106653f8...,48.0,133609168.0,0x76ba3ec5f5adbf1c58c91e86502232317eea72de,0xa4420ebbce47b452ff68d0ffa4efc8cac75655eb,2.294248,True
114830,8489,0xa4b1_0xa4420ebbce47b452ff68d0ffa4efc8cac75655eb,0xa4420ebbce47b452ff68d0ffa4efc8cac75655eb,0xa4b1,"{'1688688000': 5, '1689465600': 4, '1689638400...",{'0x912ce59144191c1204e64559fe8253a0e49e6548':...,27.317898,{'0x912ce59144191c1204e64559fe8253a0e49e6548':...,"{'1698105600': 1914.176645849158, '1698192000'...","{'1688728407': 0.0, '1691262707': 0.0, '169126...",...,NaN,201668.0,0x0d914606f3424804fa1bbbe56ccc3416733acec6,0x56c6401129b4f703996e63f21e4529d07808106653f8...,44.0,133609168.0,0x76ba3ec5f5adbf1c58c91e86502232317eea72de,0xa4420ebbce47b452ff68d0ffa4efc8cac75655eb,1.088542,True
114831,8492,0xa4b1_0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xa4b1,"{'1688688000': 4, '1688774400': 2, '1690588800...",{'0x031d35296154279dc1984dcd93e392b1f946737b':...,754.837425,{'0x031d35296154279dc1984dcd93e392b1f946737b':...,"{'1698105600': 21.30410633999788, '1698192000'...","{'1695903758': 0.0, '1695903931': 1047.4915120...",...,NaN,318528.0,0x0df5dfd95966753f01cb80e76dc20ea958238c46,0x6ace54100d28d4cbe2cb6de40a6b1e3feadbda53a83c...,7.0,135434255.0,0x0000000000000000000000000000000000000000,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,1.300000,True
114832,8492,0xa4b1_0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xa4b1,"{'1688688000': 4, '1688774400': 2, '1690588800...",{'0x031d35296154279dc1984dcd93e392b1f946737b':...,754.837425,{'0x031d35296154279dc1984dcd93e392b1f946737b':...,"{'1698105600': 21.30410633999788, '1698192000'...","{'1695903758': 0.0, '1695903931': 1047.4915120...",...,NaN,318565.0,0x107583adaa37dfd1cc0bf577183bf91351d07413,0xfeaf87ac3f7d37270abd3cee1f9922b79251fc94078b...,8.0,135434953.0,0x0000000000000000000000000000000000000000,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,1046.445067,True
114833,8493,0xa4b1_0xa841791f529f46755e129b0e16ec624e28f4c1ce,0xa841791f529f46755e129b0e16ec624e28f4c1ce,0xa4b1,"{'1688688000': 1, '1689206400': 5, '1690156800...",{'0x289ba1701c2f088cf0faf8b3705246331cb8a839':...,2.905276,{'0x289ba1701c2f088cf0faf8b3705246331cb8a839':...,"{'1698105600': 0.0, '1698192000': 2.3878833419...","{'1693393374': 0.0, '1693393484': 0.0, '169544...",...,NaN,368728.0,0x7c2e0f792ea5b4a4dbd7fa7f949cf39a5c0ba185,0x68d6f8c3ac02b39c902dd6bc7817c480066d91d654f8...,3.0,136225547.0,0x0000000000000000000000000000000000000000,0xa841791f529f46755e129b0e16ec624e28f4c1ce,300.000000,True

In [ ]:
[(i, len(wallet_project[i].drop_duplicates())) for i in wallet_project.columns]

[('Unnamed: 0', 6090),
 ('_id', 6090),
 ('address', 6083),
 ('chainId', 3),
 ('dailyAllTransactions', 6090),
 ('tokens', 6063),
 ('balanceInUSD', 5981),
 ('tokenChangeLogs', 6067),
 ('balanceChangeLogs', 5985),
 ('borrowChangeLogs', 6090),
 ('borrowInUSD', 3075),
 ('borrowTokenChangeLogs', 6090),
 ('borrowTokens', 4047),
 ('dailyNumberOfTransactions', 5453),
 ('dailyTransactionAmounts', 5805),
 ('depositChangeLogs', 6090),
 ('depositInUSD', 5017),
 ('depositTokenChangeLogs', 6090),
 ('depositTokens', 5409),
 ('liquidationLogs', 101),
 ('numberOfLiquidation', 11),
 ('totalValueOfLiquidation', 100),
 ('flagged', 19),
 ('Unnamed: 0_project', 23),
 ('_id_project', 23),
 ('idDApp_project', 2),
 ('imgUrl_project', 23),
 ('name_project', 23),
 ('category_project', 6),
 ('deployedChains_project', 15),
 ('numberOfUsers_project', 2),
 ('numberOfTransactions_project', 2),
 ('transactionVolume_project', 2),
 ('socialSignal_project', 2),
 ('sources_project', 4),
 ('id_project', 23),
 ('tvl_project', 23),
 ('subprojects_project', 2),
 ('idDefiLlama_project', 23),
 ('rankTVL_project', 17),
 ('marketShare_project', 17),
 ('tvlChangeLogs_project', 23),
 ('lastUpdated_project', 7),
 ('lastUpdatedAt_project', 3),
 ('idOpensea_project', 1),
 ('price_project', 1),
 ('volume_project', 1),
 ('volumeChangeRate_project', 1),
 ('numberOfOwners_project', 1),
 ('numberOfItems_project', 1),
 ('numberOfListedItems_project', 1),
 ('priceChangeLogs_project', 1),
 ('volumeChangeLogs_project', 1),
 ('links_project', 20),
 ('description_project', 22),
 ('infoChecked_project', 1),
 ('nftAddresses_project', 1),
 ('tokenAddresses_project', 21),
 ('rankNFT_project', 1),
 ('marketShareNFT_project', 1),
 ('idBinance_project', 1),
 ('priceChangeRate_project', 1),
 ('tvlChangeRate_project', 21),
 ('idCMC_project', 14),
 ('dexVolume_project', 14),
 ('launchedAt_project', 5),
 ('dexVolumeChangeLogs_project', 14),
 ('socialAccounts_project', 23),
 ('spotVolume_project', 14),
 ('derivativeVolume_project', 2),
 ('spotVolumeChangeLogs_project', 14),
 ('derivativeVolumeChangeLogs_project', 4),
 ('rankExchange_project', 14),
 ('marketShareExchange_project', 14),
 ('tradingVolume_project', 14),
 ('tradingVolumeChangeLogs_project', 14),
 ('symbol_project', 1),
 ('forkedFrom_project', 7),
 ('rankDefi_project', 22),
 ('marketShareDefi_project', 22),
 ('capPerTVL_project', 7),
 ('coinId_project', 15),
 ('contractAddresses_project', 23),
 ('tvlByChains_project', 20),
 ('tvlByChainsChangeLogs_project', 20),
 ('parentProtocol_project', 9),
 ('totalUsers_project', 6),
 ('totalUsersByChains_project', 6),
 ('avgLiquidity_project', 1),
 ('weeklyVisits_project', 1),
 ('spotMarkets_project', 1),
 ('numberOfCoin_project', 1),
 ('fiatSupported_project', 1),
 ('spotVolumeGraph_project', 1),
 ('numberOfCoins_project', 1),
 ('spotVolumeGraphIncrease_project', 1),
 ('supportedTokenAddresses_project', 1),
 ('spotVolumeChangeRate_project', 1),
 ('walletAddresses_project', 1),
 ('makerFeesRate_project', 1),
 ('takerFeesRate_project', 1),
 ('derivativeMarkets_project', 1),
 ('openInterests_project', 1),
 ('oldImgUrl_project', 1),
 ('derivativeVolumeChangeRate_project', 1),
 ('dexVolumeChangeRate_project', 1),
 ('deployChains_project', 1),
 ('new_addresses_project', 296),
 ('Unnamed: 0_contract', 296),
 ('_id_contract', 296),
 ('address_contract', 189),
 ('chainId_contract', 7),
 ('numberOfLastDayCalls_contract', 27),
 ('numberOfLastDayActiveUsers_contract', 26),
 ('numberOfDailyCalls_contract', 260),
 ('numberOfThisMonthCalls_contract', 97),
 ('lastUpdatedAt_contract', 72),
 ('numberOfDailyActiveUsers_contract', 257),
 ('checkTag_contract', 2),
 ('tags_contract', 8),
 ('name_contract', 169),
 ('projectDapp_contract', 5),
 ('tokenDailyTransfers_contract', 289),
 ('idCoingecko_contract', 35),
 ('keyABI_contract', 162),
 ('symbol_contract', 28),
 ('decimals_contract', 5),
 ('imgUrl_contract', 35),
 ('socialAccounts_contract', 8),
 ('lastUpdated_contract', 36),
 ('categories_contract', 30),
 ('price_contract', 27),
 ('marketCap_contract', 2),
 ('tradingVolume_contract', 5),
 ('priceChangeLogs_contract', 45),
 ('marketCapChangeLogs_contract', 45),
 ('tradingVolumeChangeLogs_contract', 45),
 ('priceChangeRate_contract', 27),
 ('numberOfHolders_contract', 48),
 ('totalSupply_contract', 6),
 ('abi_contract', 2),
 ('createdAt_contract', 9),
 ('exchanges_contract', 3),
 ('project_contract', 7),
 ('url_contract', 8),
 ('last_updated_at_contract', 1),
 ('tokenHealth_contract', 1),
 ('lendingInfo_contract', 1),
 ('contracts_contract', 1),
 ('rewardToken_contract', 1),
 ('isNew_contract', 2),
 ('token_contract', 1),
 ('note_contract', 1),
 ('topHolders_contract', 8),
 ('fee_contract', 1),
 ('Unnamed: 0_transact', 26861),
 ('contract_address_transact', 189),
 ('transaction_hash_transact', 23567),
 ('log_index_transact', 213),
 ('block_number_transact', 23517),
 ('from_address_transact', 4206),
 ('to_address_transact', 327),
 ('value_transact', 21398),
 ('is_sender', 2)]

In [ ]:
cols = ["_id","_id_contract","transaction_hash_transact"]
len(wallet_project[cols].drop_duplicates())

70512

In [ ]:
wallet_project_full = wallet_project.merge(wallet_project_1, on = ["_id","_id_contract","transaction_hash_transact"],how="outer")

In [ ]:
wallet_project_full

/usr/local/lib/python3.10/dist-packages/IPython/lib/pretty.py:700: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  output = repr(obj)
/usr/local/lib/python3.10/dist-packages/google/colab/_interactive_table_hint_button.py:178: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  df_html=dataframe._repr_html_(),  # pylint: disable=protected-access

,Unnamed: 0_x,_id,address_x,chainId_x,dailyAllTransactions_x,tokens_x,balanceInUSD_x,tokenChangeLogs_x,balanceChangeLogs_x,borrowChangeLogs_x,...,topHolders_contract_y,fee_contract_y,Unnamed: 0_transact_y,contract_address_transact_y,log_index_transact_y,block_number_transact_y,from_address_transact_y,to_address_transact_y,value_transact_y,is_receiver
0,0.0,0xa4b1_0x13f54c374a08137f542482358e2e9677c3eedce3,0x13f54c374a08137f542482358e2e9677c3eedce3,0xa4b1,"{'1688860800': 11, '1691366400': 5, '169145280...",{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,42.896319,{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,"{'1698105600': 1.1134835866233035, '1698192000...","{'1688943589': 0.0, '1688943717': 699.8712, '1...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0xa4b1_0x13f54c374a08137f542482358e2e9677c3eedce3,0x13f54c374a08137f542482358e2e9677c3eedce3,0xa4b1,"{'1688860800': 11, '1691366400': 5, '169145280...",{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,42.896319,{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,"{'1698105600': 1.1134835866233035, '1698192000...","{'1688943589': 0.0, '1688943717': 699.8712, '1...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0xa4b1_0x13f54c374a08137f542482358e2e9677c3eedce3,0x13f54c374a08137f542482358e2e9677c3eedce3,0xa4b1,"{'1688860800': 11, '1691366400': 5, '169145280...",{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,42.896319,{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,"{'1698105600': 1.1134835866233035, '1698192000...","{'1688943589': 0.0, '1688943717': 699.8712, '1...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,0xa4b1_0x13f54c374a08137f542482358e2e9677c3eedce3,0x13f54c374a08137f542482358e2e9677c3eedce3,0xa4b1,"{'1688860800': 11, '1691366400': 5, '169145280...",{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,42.896319,{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,"{'1698105600': 1.1134835866233035, '1698192000...","{'1688943589': 0.0, '1688943717': 699.8712, '1...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,0xa4b1_0x13f54c374a08137f542482358e2e9677c3eedce3,0x13f54c374a08137f542482358e2e9677c3eedce3,0xa4b1,"{'1688860800': 11, '1691366400': 5, '169145280...",{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,42.896319,{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,"{'1698105600': 1.1134835866233035, '1698192000...","{'1688943589': 0.0, '1688943717': 699.8712, '1...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164651,NaN,0xa4b1_0xa4420ebbce47b452ff68d0ffa4efc8cac75655eb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,201669.0,0xd69d402d1bdb9a2b8c3d88d98b9ceaf9e4cd72d9,48.0,133609168.0,0x76ba3ec5f5adbf1c58c91e86502232317eea72de,0xa4420ebbce47b452ff68d0ffa4efc8cac75655eb,2.294248,True
164652,NaN,0xa4b1_0xa4420ebbce47b452ff68d0ffa4efc8cac75655eb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,201668.0,0x0d914606f3424804fa1bbbe56ccc3416733acec6,44.0,133609168.0,0x76ba3ec5f5adbf1c58c91e86502232317eea72de,0xa4420ebbce47b452ff68d0ffa4efc8cac75655eb,1.088542,True
164653,NaN,0xa4b1_0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,318528.0,0x0df5dfd95966753f01cb80e76dc20ea958238c46,7.0,135434255.0,0x0000000000000000000000000000000000000000,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,1.300000,True
164654,NaN,0xa4b1_0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,318565.0,0x107583adaa37dfd1cc0bf577183bf91351d07413,8.0,135434953.0,0x0000000000000000000000000000000000000000,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,1046.445067,True
164655,NaN,0xa4b1_0xa841791f529f46755e129b0e16ec624e28f4c1ce,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,368728.0,0x7c2e0f792ea5b4a4dbd7fa7f949cf39a5c0ba185,3.0,136225547.0,0x0000000000000000000000000000000000000000,0xa841791f529f46755e129b0e16ec624e28f4c1ce,300.000000,True

In [ ]:
# wallet_project_full["_id"].drop_duplicates()
wallet_project_full = wallet_project_full[(wallet_project_full["_id_project"].notnull())]

KeyError: ignored

In [ ]:
wallet_project_full['type'] = 'single_chain'

<ipython-input-140-a2993453ac21>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wallet_project_full['type'] = 'single_chain'

In [ ]:
wallet_project_full

,Unnamed: 0,_id,address,chainId,dailyAllTransactions,tokens,balanceInUSD,tokenChangeLogs,balanceChangeLogs,borrowChangeLogs,...,contract_address_transact,transaction_hash_transact,log_index_transact,block_number_transact,from_address_transact,to_address_transact,value_transact,is_sender,is_receiver,type
0,0.0,0xa4b1_0x13f54c374a08137f542482358e2e9677c3eedce3,0x13f54c374a08137f542482358e2e9677c3eedce3,0xa4b1,"{'1688860800': 11, '1691366400': 5, '169145280...",{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,42.896319,{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,"{'1698105600': 1.1134835866233035, '1698192000...","{'1688943589': 0.0, '1688943717': 699.8712, '1...",...,0x8619d80fb0141ba7f184cbf22fd724116d9f7ffc,0x80a10325f3a223fdeaff60aefc7e7348d139ab77d4ac...,0.0,137752197.0,0x13f54c374a08137f542482358e2e9677c3eedce3,0x0000000000000000000000000000000000000000,1002.165002,True,NaN,single_chain
1,0.0,0xa4b1_0x13f54c374a08137f542482358e2e9677c3eedce3,0x13f54c374a08137f542482358e2e9677c3eedce3,0xa4b1,"{'1688860800': 11, '1691366400': 5, '169145280...",{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,42.896319,{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,"{'1698105600': 1.1134835866233035, '1698192000...","{'1688943589': 0.0, '1688943717': 699.8712, '1...",...,0x8619d80fb0141ba7f184cbf22fd724116d9f7ffc,0x80a10325f3a223fdeaff60aefc7e7348d139ab77d4ac...,0.0,137752197.0,0x13f54c374a08137f542482358e2e9677c3eedce3,0x0000000000000000000000000000000000000000,1002.165002,True,NaN,single_chain
2,0.0,0xa4b1_0x13f54c374a08137f542482358e2e9677c3eedce3,0x13f54c374a08137f542482358e2e9677c3eedce3,0xa4b1,"{'1688860800': 11, '1691366400': 5, '169145280...",{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,42.896319,{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,"{'1698105600': 1.1134835866233035, '1698192000...","{'1688943589': 0.0, '1688943717': 699.8712, '1...",...,0x8619d80fb0141ba7f184cbf22fd724116d9f7ffc,0x80a10325f3a223fdeaff60aefc7e7348d139ab77d4ac...,0.0,137752197.0,0x13f54c374a08137f542482358e2e9677c3eedce3,0x0000000000000000000000000000000000000000,1002.165002,True,NaN,single_chain
3,0.0,0xa4b1_0x13f54c374a08137f542482358e2e9677c3eedce3,0x13f54c374a08137f542482358e2e9677c3eedce3,0xa4b1,"{'1688860800': 11, '1691366400': 5, '169145280...",{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,42.896319,{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,"{'1698105600': 1.1134835866233035, '1698192000...","{'1688943589': 0.0, '1688943717': 699.8712, '1...",...,0x8619d80fb0141ba7f184cbf22fd724116d9f7ffc,0x80a10325f3a223fdeaff60aefc7e7348d139ab77d4ac...,0.0,137752197.0,0x13f54c374a08137f542482358e2e9677c3eedce3,0x0000000000000000000000000000000000000000,1002.165002,True,NaN,single_chain
4,0.0,0xa4b1_0x13f54c374a08137f542482358e2e9677c3eedce3,0x13f54c374a08137f542482358e2e9677c3eedce3,0xa4b1,"{'1688860800': 11, '1691366400': 5, '169145280...",{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,42.896319,{'0xff970a61a04b1ca14834a43f5de4533ebddb5cc8':...,"{'1698105600': 1.1134835866233035, '1698192000...","{'1688943589': 0.0, '1688943717': 699.8712, '1...",...,0x8619d80fb0141ba7f184cbf22fd724116d9f7ffc,0x80a10325f3a223fdeaff60aefc7e7348d139ab77d4ac...,0.0,137752197.0,0x13f54c374a08137f542482358e2e9677c3eedce3,0x0000000000000000000000000000000000000000,1002.165002,True,NaN,single_chain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74674,8487.0,0xa4b1_0xa1e639fe9f581bfe1bfbd50b4fb2167cfff11e94,0xa1e639fe9f581bfe1bfbd50b4fb2167cfff11e94,0xa4b1,"{'1688774400': 2, '1696464000': 13, '169655040...",{'0x0000000000000000000000000000000000000000':...,34.812515,{'0x0000000000000000000000000000000000000000':...,"{'1700006400': 29.249538524746576, '1700092800...","{'1696562152': 1.601677, '1696562237': 11.6016...",...,0x7c2e0f792ea5b4a4dbd7fa7f949cf39a5c0ba185,0x24b83ab1290eca58e8269b7471ce2eeb70615ec0c6a1...,2.0,137953063.0,0xa1e639fe9f581bfe1bfbd50b4fb2167cfff11e94,0x0000000000000000000000000000000000000000,11.601678,True,NaN,single_chain
74677,8492.0,0xa4b1_0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xa4b1,"{'1688688000': 4, '1688774400': 2, '1690588800...",{'0x031d35296154279dc1984dcd93e392b1f946737b':...,754.837425,{'0x031d35296154279dc1984dcd93e392b1f946737b':...,"{'1698105600': 21.30410633999788, '1698192000'...","{'1695903758': 0.0, '1695903931': 1047.4915120...",...,0x6694340fc020c5e6b96567843da2df01b2ce1eb6,0xe92eb1eda1e4fd029d2cdc52447dda56b072a8919cb5...,10.0,135970802.0,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xd49de5771d82ffe9691aa26f47766a15588acaa2,3.986631,True,NaN,single_chain
74678,8492.0,0xa4b1_0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xa4b1,"{'1688688000': 4, '1688774400': 2, '1690588800...",{'0x031d35296154279dc1984dcd93e392b1f946737b':...,754.837425,{'0x031d35296154279dc1984dcd93e392b1f946737b':...,"{'1698105600': 21.30410633999788, '1698192000'...","{'1695903758': 0.0, '1695903931': 1047.4915120...",...,0x0df5dfd95966753f01cb80e76dc20ea958238c46,0xb86c468f4ed96b4396c0b240227054c5205f2cb32904...,11.0,135656205.0,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xbb5ca40b2f7af3b1ff5dbce0e9cc78f8bfa817ce,1.300037,True,NaN,single_chain
74679,8492.0,0xa4b1_0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xa4b1,"{'1688688000': 4, '1688774400': 2, '1690588800...",{'0x031d35296154279dc1984dcd93e392b1f946737b':...,754.837425,{'0x031d35296154279dc1984dcd93e392b1f946737b':...,"{'1698105600': 21.30410633999788, '1698192000'...","{'1695903758': 0.0, '1695903931': 1047.4915120...",...,0x107583adaa37dfd1cc0bf577183bf91351d07413,0x9ac37302a68925408c3a8932bae720afec45692bebab...,21.0,135456110.0,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0x0000000000000000000000000000000000000000,1046.465745,True,NaN,single_chain
74680,8493.0,0xa4b1_0xa841791f529f46755e129b0e16ec624e28f4c1ce,0xa841791f529f46755e129b0e16ec624e28f4c1ce,0xa4b1,"{'1688688000': 1, '1689206400': 5, '1690156800...",{'0x289ba1701c2f088cf0faf8b3705246331cb8a839':...,2.905276,{'0x289ba1701c2f088cf0faf8b3705246331cb8a839':...,"{'1698105600': 0.0, '1698192000': 2.3878833419...","{'1693393374': 0.0, '1693393484': 0.0, '169544...",...,0x2dade5b7df9da3a7e1c9748d169cd6dff77e3d01,0x4acb4e619fb375e51f883140e8fa21d5d683b34ecb1b...,5.0,133715410.0,0xa841791f529f46755e129b0e16ec624e28f4c1ce,0x0000000000000000000000000000000000000000,374.000000,True,NaN,single_chain

In [ ]:
multichain_wallet_project = multichain_wallets.merge(transact_project, left_on ="address", right_on="from_address_transact", how='left',suffixes=('_sender', ''))
multichain_wallet_project["is_sender"] = multichain_wallet_project['from_address_transact'].notnull()

multichain_wallet_project_1 = multichain_wallets.merge(transact_project, left_on ="address", right_on="to_address_transact", how='left',suffixes=('_receiver',''))
multichain_wallet_project_1["is_receiver"] = multichain_wallet_project_1['to_address_transact'].notnull()

multichain_wallet_project_full = multichain_wallet_project.merge(multichain_wallet_project_1[["_id","_id_contract","transaction_hash_transact","is_receiver"]], on = ["_id","_id_contract","transaction_hash_transact"],how="outer")
multichain_wallet_project_full = multichain_wallet_project_full[(multichain_wallet_project_full["_id_project"].notnull())]

In [ ]:
multichain_wallet_project_full['type'] = 'multichain_wallet'
multichain_wallet_project_full

,Unnamed: 0,_id,address,tokens,balanceInUSD,tokenChangeLogs,balanceChangeLogs,borrowChangeLogs,borrowInUSD,borrowTokenChangeLogs,...,contract_address_transact,transaction_hash_transact,log_index_transact,block_number_transact,from_address_transact,to_address_transact,value_transact,is_sender,is_receiver,type
2,2.0,0x8daaa78bf8fc2d19fbb3b88319325607460387a3,0x8daaa78bf8fc2d19fbb3b88319325607460387a3,{},0.000000,{},{},{'1677146111': 0},0.0,{'0x1_0xc02aaa39b223fe8d0a0e5c4f27ead9083c756c...,...,0x6694340fc020c5e6b96567843da2df01b2ce1eb6,0x1ec44e2eabc78bcbd53785972e52fcf6761671c097bd...,0.0,130063745.0,0x8daaa78bf8fc2d19fbb3b88319325607460387a3,0x0000000000000000000000000000000000000000,20.130082,True,NaN,multichain_wallet
3,3.0,0xdacfe9e62dff6487458f64092aed45a2c9599740,0xdacfe9e62dff6487458f64092aed45a2c9599740,{},0.000000,{},{},{'1677146111': 0},0.0,{'0x1_0xc02aaa39b223fe8d0a0e5c4f27ead9083c756c...,...,0x6694340fc020c5e6b96567843da2df01b2ce1eb6,0x31da687e300b100d14b4416f2deca8822ea2b6b886f4...,0.0,130063593.0,0xdacfe9e62dff6487458f64092aed45a2c9599740,0x0000000000000000000000000000000000000000,63.269286,True,NaN,multichain_wallet
5,5.0,0xb7fac33f47af1160ba17eb82e7202584f73a8fad,0xb7fac33f47af1160ba17eb82e7202584f73a8fad,{'0xa4b1_0x00000000000000000000000000000000000...,692.931648,{'0xa4b1_0x00000000000000000000000000000000000...,"{'1698105600': 1071.399196279791, '1698192000'...",{'1702011653': 0},0.0,{'0x38_0x0000000000000000000000000000000000000...,...,0x6694340fc020c5e6b96567843da2df01b2ce1eb6,0x5eb9e583e9774bd27ebc9c126e217630918fdc921adc...,9.0,136676196.0,0xb7fac33f47af1160ba17eb82e7202584f73a8fad,0x35946e91aed5b4b8992b773f251356798888b5c2,20.699905,True,NaN,multichain_wallet
6,6.0,0xb02fa29bfd054db5514115533b6fac39dac75391,0xb02fa29bfd054db5514115533b6fac39dac75391,{'0x89_0x0000000000000000000000000000000000000...,2.851570,{'0x89_0x0000000000000000000000000000000000000...,"{'1699228800': 4.593658364905137, '1699315200'...",{'1701516056': 0},0.0,{'0x1_0x00000000000000000000000000000000000000...,...,0x32df62dc3aed2cd6224193052ce665dc18165841,0x24b5ff0b4bdde7e1807df7e16e3974a8bef34bc6c4b0...,1.0,136880612.0,0xb02fa29bfd054db5514115533b6fac39dac75391,0x0000000000000000000000000000000000000000,4.714643,True,NaN,multichain_wallet
7,7.0,0x3a95ac31729140d6ac25c80b90eceec9b929eb9e,0x3a95ac31729140d6ac25c80b90eceec9b929eb9e,{'0x89_0x0000000000000000000000000000000000000...,14.632724,{'0x89_0x0000000000000000000000000000000000000...,"{'1699228800': 459.26867156756487, '1699315200...",{'1699111620': 0},0.0,{'0x1_0xc02aaa39b223fe8d0a0e5c4f27ead9083c756c...,...,0x0c1cf6883efa1b496b01f654e247b9b419873054,0xc4fed83aad531c4a3a1bcc016e035e24537b0541409b...,0.0,136883371.0,0x3a95ac31729140d6ac25c80b90eceec9b929eb9e,0x0c1cf6883efa1b496b01f654e247b9b419873054,0.011609,True,NaN,multichain_wallet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326039,8350.0,0x868904b1681ca6b0c56363f0f57d35eee36bdd63,0x868904b1681ca6b0c56363f0f57d35eee36bdd63,{'0x1_0x00000000000000000000000000000000000000...,17.909880,{'0x1_0x00000000000000000000000000000000000000...,"{'1699228800': 124.14973426014654, '1699315200...",{'1697708455': 0},0.0,{'0x89_0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1...,...,0x0df5dfd95966753f01cb80e76dc20ea958238c46,0xa79280d871d6ace7f1ef1130469e01378a7fcb3711b9...,12.0,132264247.0,0x868904b1681ca6b0c56363f0f57d35eee36bdd63,0x0000000000000000000000000000000000000000,0.000472,True,NaN,multichain_wallet
326040,8350.0,0x868904b1681ca6b0c56363f0f57d35eee36bdd63,0x868904b1681ca6b0c56363f0f57d35eee36bdd63,{'0x1_0x00000000000000000000000000000000000000...,17.909880,{'0x1_0x00000000000000000000000000000000000000...,"{'1699228800': 124.14973426014654, '1699315200...",{'1697708455': 0},0.0,{'0x89_0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1...,...,0xab04c0841f39596c9f18a981a2bd32f63ab7a817,0xa79280d871d6ace7f1ef1130469e01378a7fcb3711b9...,4.0,132264247.0,0x868904b1681ca6b0c56363f0f57d35eee36bdd63,0x0000000000000000000000000000000000000000,0.006294,True,NaN,multichain_wallet
326043,8353.0,0xecb6da7d4d5e76fe6f925921bdfd4bc1def1abe8,0xecb6da7d4d5e76fe6f925921bdfd4bc1def1abe8,{'0x89_0x0000000000000000000000000000000000000...,8.930732,{'0x89_0x0000000000000000000000000000000000000...,"{'1699228800': 6.875329161356275, '1699315200'...",{},0.0,{},...,0x6694340fc020c5e6b96567843da2df01b2ce1eb6,0xa9725488a8296dbc6a4531e8db36bec846978f2693a6...,0.0,132474254.0,0xecb6da7d4d5e76fe6f925921bdfd4bc1def1abe8,0x0000000000000000000000000000000000000000,117.031387,True,NaN,multichain_wallet
326045,8355.0,0xe030fec019fe9cbab01eab3106eb9ce32851e64d,0xe030fec019fe9cbab01eab3106eb9ce32851e64d,{'0x89_0x0000000000000000000000000000000000000...,106.024045,{'0x89_0x0000000000000000000000000000000000000...,"{'1699228800': 20450.158481606937, '1699315200...",{'1701015335': 0},0.0,{'0xa4b1_0x2f2a2543b76a4166549f7aab2e75bef0aef...,...,0x0df5dfd95966753f01cb80e76dc20ea958238c46,0xbeab4f81776cf78ec481169c39e64af1818f9eeee3c5...,3.0,135620751.0,0xe030fec019fe9cbab01eab3106eb9ce32851e64d,0xbb5ca40b2f7af3b1ff5dbce0e9cc78f8bfa817ce,0.002441,True,NaN,multichain_wallet
326047,8357.0,0x77f331dbba4093e6da9e0e0e1ca94922cb3382ff,0x77f331dbba4093e6da9e0e0e1ca94922cb3382ff,{'0x1_0x00000000000000000000000000000000000000...,229.784273,{'0x1_0x00000000000000000000000000000000000000...,"{'1699228800': 511.51471781012054, '1699315200...",{'1699043018': 0},0.0,{'0xa4b1_0x2f2a2543b76a4166549f7aab2e75bef0aef...,...,0xab04c0841f39596c9f18a981a2bd32f63ab7a817,0x2cacacb78cad8fdda7e2c5d50cde6e63e5a351e5e4f1...,13.0,134808288.0,0x77f331dbba4093e6da9e0e0e1ca94922cb3382ff,0x0000000000000000000000000000000000000000,0.013440,True,NaN,multichain_wallet

In [ ]:
print(len(multichain_wallet_project_full["_id"].drop_duplicates()))
print(len(wallet_project_full["_id"].drop_duplicates()))

4836
4209

In [ ]:
all_wallet= pd.concat([multichain_wallet_project_full,wallet_project_full])

In [ ]:
all_wallet.drop_duplicates(["_id","_id_project"])

,Unnamed: 0,_id,address,tokens,balanceInUSD,tokenChangeLogs,balanceChangeLogs,borrowChangeLogs,borrowInUSD,borrowTokenChangeLogs,...,log_index_transact,block_number_transact,from_address_transact,to_address_transact,value_transact,is_sender,is_receiver,type,chainId,dailyAllTransactions
2,2.0,0x8daaa78bf8fc2d19fbb3b88319325607460387a3,0x8daaa78bf8fc2d19fbb3b88319325607460387a3,{},0.000000,{},{},{'1677146111': 0},0.000000,{'0x1_0xc02aaa39b223fe8d0a0e5c4f27ead9083c756c...,...,0.0,130063745.0,0x8daaa78bf8fc2d19fbb3b88319325607460387a3,0x0000000000000000000000000000000000000000,20.130082,True,NaN,multichain_wallet,NaN,NaN
3,3.0,0xdacfe9e62dff6487458f64092aed45a2c9599740,0xdacfe9e62dff6487458f64092aed45a2c9599740,{},0.000000,{},{},{'1677146111': 0},0.000000,{'0x1_0xc02aaa39b223fe8d0a0e5c4f27ead9083c756c...,...,0.0,130063593.0,0xdacfe9e62dff6487458f64092aed45a2c9599740,0x0000000000000000000000000000000000000000,63.269286,True,NaN,multichain_wallet,NaN,NaN
5,5.0,0xb7fac33f47af1160ba17eb82e7202584f73a8fad,0xb7fac33f47af1160ba17eb82e7202584f73a8fad,{'0xa4b1_0x00000000000000000000000000000000000...,692.931648,{'0xa4b1_0x00000000000000000000000000000000000...,"{'1698105600': 1071.399196279791, '1698192000'...",{'1702011653': 0},0.000000,{'0x38_0x0000000000000000000000000000000000000...,...,9.0,136676196.0,0xb7fac33f47af1160ba17eb82e7202584f73a8fad,0x35946e91aed5b4b8992b773f251356798888b5c2,20.699905,True,NaN,multichain_wallet,NaN,NaN
6,6.0,0xb02fa29bfd054db5514115533b6fac39dac75391,0xb02fa29bfd054db5514115533b6fac39dac75391,{'0x89_0x0000000000000000000000000000000000000...,2.851570,{'0x89_0x0000000000000000000000000000000000000...,"{'1699228800': 4.593658364905137, '1699315200'...",{'1701516056': 0},0.000000,{'0x1_0x00000000000000000000000000000000000000...,...,1.0,136880612.0,0xb02fa29bfd054db5514115533b6fac39dac75391,0x0000000000000000000000000000000000000000,4.714643,True,NaN,multichain_wallet,NaN,NaN
7,7.0,0x3a95ac31729140d6ac25c80b90eceec9b929eb9e,0x3a95ac31729140d6ac25c80b90eceec9b929eb9e,{'0x89_0x0000000000000000000000000000000000000...,14.632724,{'0x89_0x0000000000000000000000000000000000000...,"{'1699228800': 459.26867156756487, '1699315200...",{'1699111620': 0},0.000000,{'0x1_0xc02aaa39b223fe8d0a0e5c4f27ead9083c756c...,...,0.0,136883371.0,0x3a95ac31729140d6ac25c80b90eceec9b929eb9e,0x0c1cf6883efa1b496b01f654e247b9b419873054,0.011609,True,NaN,multichain_wallet,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74671,8484.0,0xa4b1_0x9e121698d68cf4c2b34202ccee11ea62769a8bc7,0x9e121698d68cf4c2b34202ccee11ea62769a8bc7,{'0x0000000000000000000000000000000000000000':...,397.592272,{'0x0000000000000000000000000000000000000000':...,"{'1698105600': 479.27065433986206, '1698192000...","{'1696768263': 0.0, '1697503868': 2.9322882953...",0.000000,{'0x82af49447d8a07e3bd95bd0d56f35241523fbab1':...,...,1.0,135532157.0,0x9e121698d68cf4c2b34202ccee11ea62769a8bc7,0x0000000000000000000000000000000000000000,111.900147,True,NaN,single_chain,0xa4b1,"{'1688688000': 1, '1689638400': 3, '1689897600..."
74673,8487.0,0xa4b1_0xa1e639fe9f581bfe1bfbd50b4fb2167cfff11e94,0xa1e639fe9f581bfe1bfbd50b4fb2167cfff11e94,{'0x0000000000000000000000000000000000000000':...,34.812515,{'0x0000000000000000000000000000000000000000':...,"{'1700006400': 29.249538524746576, '1700092800...","{'1696562152': 1.601677, '1696562237': 11.6016...",0.000000,{'0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9':...,...,5.0,137953138.0,0xa1e639fe9f581bfe1bfbd50b4fb2167cfff11e94,0x0000000000000000000000000000000000000000,100.000002,True,NaN,single_chain,0xa4b1,"{'1688774400': 2, '1696464000': 13, '169655040..."
74677,8492.0,0xa4b1_0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,{'0x031d35296154279dc1984dcd93e392b1f946737b':...,754.837425,{'0x031d35296154279dc1984dcd93e392b1f946737b':...,"{'1698105600': 21.30410633999788, '1698192000'...","{'1695903758': 0.0, '1695903931': 1047.4915120...",0.000000,{'0x82af49447d8a07e3bd95bd0d56f35241523fbab1':...,...,10.0,135970802.0,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xd49de5771d82ffe9691aa26f47766a15588acaa2,3.986631,True,NaN,single_chain,0xa4b1,"{'1688688000': 4, '1688774400': 2, '1690588800..."
74678,8492.0,0xa4b1_0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,{'0x031d35296154279dc1984dcd93e392b1f946737b':...,754.837425,{'0x031d35296154279dc1984dcd93e392b1f946737b':...,"{'1698105600': 21.30410633999788, '1698192000'...","{'1695903758': 0.0, '1695903931': 1047.4915120...",0.000000,{'0x82af49447d8a07e3bd95bd0d56f35241523fbab1':...,...,11.0,135656205.0,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xbb5ca40b2f7af3b1ff5dbce0e9cc78f8bfa817ce,1.300037,True,NaN,single_chain,0xa4b1,"{'1688688000': 4, '1688774400': 2, '1690588800..."
74680,8493.0,0xa4b1_0xa841791f529f46755e129b0e16ec624e28f4c1ce,0xa841791f529f46755e129b0e16ec624e28f4c1ce,{'0x289ba1701c2f088cf0faf8b3705246331cb8a839':...,2.905276,{'0x289ba1701c2f088cf0faf8b3705246331cb8a839':...,"{'1698105600': 0.0, '1698192000': 2.3878833419...","{'1693393374': 0.0, '1693393484': 0.0, '169544...",300.000001,{'0x912ce59144191c1204e64559fe8253a0e49e6548':...,...,5.0,133715410.0,0xa841791f529f46755e129b0e16ec624e28f4c1ce,0x0000000000000000000000000000000000000000,374.000000,True,NaN,single_chain,0xa4b1,"{'1688688000': 1, '1689206400': 5, '1690156800..."

In [ ]:
# all_wallet = all_wallet.rename(columns = {

# })
all_wallet[all_wallet["is_sender"].isnull()]

Empty DataFrame
Columns: [Unnamed: 0, _id, address, tokens, balanceInUSD, tokenChangeLogs, balanceChangeLogs, borrowChangeLogs, borrowInUSD, borrowTokenChangeLogs, borrowTokens, dailyNumberOfTransactions, dailyTransactionAmounts, depositChangeLogs, depositInUSD, depositTokenChangeLogs, depositTokens, liquidationLogs, numberOfLiquidation, totalValueOfLiquidation, flagged, Unnamed: 0_project, _id_project, idDApp_project, imgUrl_project, name_project, category_project, deployedChains_project, numberOfUsers_project, numberOfTransactions_project, transactionVolume_project, socialSignal_project, sources_project, id_project, tvl_project, subprojects_project, idDefiLlama_project, rankTVL_project, marketShare_project, tvlChangeLogs_project, lastUpdated_project, lastUpdatedAt_project, idOpensea_project, price_project, volume_project, volumeChangeRate_project, numberOfOwners_project, numberOfItems_project, numberOfListedItems_project, priceChangeLogs_project, volumeChangeLogs_project, links_project, description_project, infoChecked_project, nftAddresses_project, tokenAddresses_project, rankNFT_project, marketShareNFT_project, idBinance_project, priceChangeRate_project, tvlChangeRate_project, idCMC_project, dexVolume_project, launchedAt_project, dexVolumeChangeLogs_project, socialAccounts_project, spotVolume_project, derivativeVolume_project, spotVolumeChangeLogs_project, derivativeVolumeChangeLogs_project, rankExchange_project, marketShareExchange_project, tradingVolume_project, tradingVolumeChangeLogs_project, symbol_project, forkedFrom_project, rankDefi_project, marketShareDefi_project, capPerTVL_project, coinId_project, contractAddresses_project, tvlByChains_project, tvlByChainsChangeLogs_project, parentProtocol_project, totalUsers_project, totalUsersByChains_project, avgLiquidity_project, weeklyVisits_project, spotMarkets_project, numberOfCoin_project, fiatSupported_project, spotVolumeGraph_project, numberOfCoins_project, spotVolumeGraphIncrease_project, supportedTokenAddresses_project, spotVolumeChangeRate_project, walletAddresses_project, makerFeesRate_project, takerFeesRate_project, derivativeMarkets_project, ...]
Index: []

[0 rows x 166 columns]

In [ ]:
!zip wallet_merged.zip /content/wallet_classification.csv

  adding: content/wallet_classification.csv (deflated 98%)

In [ ]:
# with open("draft.txt","w") as f:
#   f.writelines([i + "\n" for i in all_wallet.columns.tolist()])

# Clean

In [ ]:
# thêm cột numberOfToken, numberOfDepositToken,
# numberOfBorrowToken, numberOfTimeSender, numberOfTimeReceiver
# numberOfContract, most frequent contract, least frequent contract
# most freq ammount in transfer, mean , min, max transaction,
with open("/content/wallet_classification.txt", "r") as f:
  columns = [i.replace("\n","") for i in f.readlines()]

# Missing value
all_wallet["is_receiver"] =all_wallet["is_receiver"].fillna(value = False)
all_wallet["chainId"] =all_wallet["chainId"].fillna(value = "multichain")

# all_wallet[columns]
# column = []
all_wallet
# all_wallet[all_wallet[column].notnull()]#.sort_values("balanceInUSD")

,Unnamed: 0,_id,address,tokens,balanceInUSD,tokenChangeLogs,balanceChangeLogs,borrowChangeLogs,borrowInUSD,borrowTokenChangeLogs,...,log_index_transact,block_number_transact,from_address_transact,to_address_transact,value_transact,is_sender,is_receiver,type,chainId,dailyAllTransactions
2,2.0,0x8daaa78bf8fc2d19fbb3b88319325607460387a3,0x8daaa78bf8fc2d19fbb3b88319325607460387a3,{},0.000000,{},{},{'1677146111': 0},0.000000,{'0x1_0xc02aaa39b223fe8d0a0e5c4f27ead9083c756c...,...,0.0,130063745.0,0x8daaa78bf8fc2d19fbb3b88319325607460387a3,0x0000000000000000000000000000000000000000,20.130082,True,False,multichain_wallet,multichain,NaN
3,3.0,0xdacfe9e62dff6487458f64092aed45a2c9599740,0xdacfe9e62dff6487458f64092aed45a2c9599740,{},0.000000,{},{},{'1677146111': 0},0.000000,{'0x1_0xc02aaa39b223fe8d0a0e5c4f27ead9083c756c...,...,0.0,130063593.0,0xdacfe9e62dff6487458f64092aed45a2c9599740,0x0000000000000000000000000000000000000000,63.269286,True,False,multichain_wallet,multichain,NaN
5,5.0,0xb7fac33f47af1160ba17eb82e7202584f73a8fad,0xb7fac33f47af1160ba17eb82e7202584f73a8fad,{'0xa4b1_0x00000000000000000000000000000000000...,692.931648,{'0xa4b1_0x00000000000000000000000000000000000...,"{'1698105600': 1071.399196279791, '1698192000'...",{'1702011653': 0},0.000000,{'0x38_0x0000000000000000000000000000000000000...,...,9.0,136676196.0,0xb7fac33f47af1160ba17eb82e7202584f73a8fad,0x35946e91aed5b4b8992b773f251356798888b5c2,20.699905,True,False,multichain_wallet,multichain,NaN
6,6.0,0xb02fa29bfd054db5514115533b6fac39dac75391,0xb02fa29bfd054db5514115533b6fac39dac75391,{'0x89_0x0000000000000000000000000000000000000...,2.851570,{'0x89_0x0000000000000000000000000000000000000...,"{'1699228800': 4.593658364905137, '1699315200'...",{'1701516056': 0},0.000000,{'0x1_0x00000000000000000000000000000000000000...,...,1.0,136880612.0,0xb02fa29bfd054db5514115533b6fac39dac75391,0x0000000000000000000000000000000000000000,4.714643,True,False,multichain_wallet,multichain,NaN
7,7.0,0x3a95ac31729140d6ac25c80b90eceec9b929eb9e,0x3a95ac31729140d6ac25c80b90eceec9b929eb9e,{'0x89_0x0000000000000000000000000000000000000...,14.632724,{'0x89_0x0000000000000000000000000000000000000...,"{'1699228800': 459.26867156756487, '1699315200...",{'1699111620': 0},0.000000,{'0x1_0xc02aaa39b223fe8d0a0e5c4f27ead9083c756c...,...,0.0,136883371.0,0x3a95ac31729140d6ac25c80b90eceec9b929eb9e,0x0c1cf6883efa1b496b01f654e247b9b419873054,0.011609,True,False,multichain_wallet,multichain,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74674,8487.0,0xa4b1_0xa1e639fe9f581bfe1bfbd50b4fb2167cfff11e94,0xa1e639fe9f581bfe1bfbd50b4fb2167cfff11e94,{'0x0000000000000000000000000000000000000000':...,34.812515,{'0x0000000000000000000000000000000000000000':...,"{'1700006400': 29.249538524746576, '1700092800...","{'1696562152': 1.601677, '1696562237': 11.6016...",0.000000,{'0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9':...,...,2.0,137953063.0,0xa1e639fe9f581bfe1bfbd50b4fb2167cfff11e94,0x0000000000000000000000000000000000000000,11.601678,True,False,single_chain,0xa4b1,"{'1688774400': 2, '1696464000': 13, '169655040..."
74677,8492.0,0xa4b1_0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,{'0x031d35296154279dc1984dcd93e392b1f946737b':...,754.837425,{'0x031d35296154279dc1984dcd93e392b1f946737b':...,"{'1698105600': 21.30410633999788, '1698192000'...","{'1695903758': 0.0, '1695903931': 1047.4915120...",0.000000,{'0x82af49447d8a07e3bd95bd0d56f35241523fbab1':...,...,10.0,135970802.0,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xd49de5771d82ffe9691aa26f47766a15588acaa2,3.986631,True,False,single_chain,0xa4b1,"{'1688688000': 4, '1688774400': 2, '1690588800..."
74678,8492.0,0xa4b1_0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,{'0x031d35296154279dc1984dcd93e392b1f946737b':...,754.837425,{'0x031d35296154279dc1984dcd93e392b1f946737b':...,"{'1698105600': 21.30410633999788, '1698192000'...","{'1695903758': 0.0, '1695903931': 1047.4915120...",0.000000,{'0x82af49447d8a07e3bd95bd0d56f35241523fbab1':...,...,11.0,135656205.0,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xbb5ca40b2f7af3b1ff5dbce0e9cc78f8bfa817ce,1.300037,True,False,single_chain,0xa4b1,"{'1688688000': 4, '1688774400': 2, '1690588800..."
74679,8492.0,0xa4b1_0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,{'0x031d35296154279dc1984dcd93e392b1f946737b':...,754.837425,{'0x031d35296154279dc1984dcd93e392b1f946737b':...,"{'1698105600': 21.30410633999788, '1698192000'...","{'1695903758': 0.0, '1695903931': 1047.4915120...",0.000000,{'0x82af49447d8a07e3bd95bd0d56f35241523fbab1':...,...,21.0,135456110.0,0xa698cf22bd0e005c8fe25d8f073e0f73a911b101,0x0000000000000000000000000000000000000000,1046.465745,True,False,single_chain,0xa4b1,"{'1688688000': 4, '1688774400': 2, '1690588800..."
74680,8493.0,0xa4b1_0xa841791f529f46755e129b0e16ec624e28f4c1ce,0xa841791f529f46755e129b0e16ec624e28f4c1ce,{'0x289ba1701c2f088cf0faf8b3705246331cb8a839':...,2.905276,{'0x289ba1701c2f088cf0faf8b3705246331cb8a839':...,"{'1698105600': 0.0, '1698192000': 2.3878833419...","{'1693393374': 0.0, '1693393484': 0.0, '169544...",300.000001,{'0x912ce59144191c1204e64559fe8253a0e49e6548':...,...,5.0,133715410.0,0xa841791f529f46755e129b0e16ec624e28f4c1ce,0x0000000000000000000000000000000000000000,374.000000,True,False,single_chain,0xa4b1,"{'1688688000': 1, '1689206400': 5, '1690156800..."